In [1]:
import numpy as np

In [7]:
'''
[Type]
int8/16/32/64   int -> int32/64
uint8/16/32/64  unsigned int
float16/32/64   float -> float64
complex64/128   complex -> complex128
'''
a = np.array([1.1, 2.2], dtype='float')
print(a[0].dtype)

float64


In [6]:
# define struct dtype
student = np.dtype([('name', 'i4'), ('age', 'f4')])
s = np.array([(220, 18), (433, 20)], dtype=student)
print(s)

[(220, 18.) (433, 20.)]


In [20]:
'''
create ndarray
'''

# from list
arr1 = np.array([1, 2, 3])
arr2 = np.array([
    [1, 2, 3],
    [2, 3, 1],
    [3, 1, 2]
])
print("=== 1d ===")
print(arr1, "\n")
print("=== 2d ===")
print(arr2)

=== 1d ===
[1 2 3] 

=== 2d ===
[[1 2 3]
 [2 3 1]
 [3 1 2]]


In [13]:
# zeros(ones)
arr3 = np.zeros((2, 3))
print(arr4)

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
# 0~n
arr4 = np.arange(5)
print(arr5)

[0 1 2 3 4]


In [15]:
# 0-n 均匀分布
arr5 = np.linspace(1, 9, num=5)
print(arr6)

[1. 3. 5. 7. 9.]


In [16]:
# 单元矩阵
arr6 = np.eye(3)
print(arr7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
'''
ndarray info
'''
arr = np.array([[1, 2, 3], [2, 3, 1]])
print(arr)
print("length:\t", arr.size)
print("B/item:\t", arr.itemsize)
print("shape:\t", arr.shape)

[[1 2 3]
 [2 3 1]]
length:	 6
B/item:	 4
shape:	 (2, 3)


In [33]:
'''
reshape
'''
arr = np.array([1, 2, 3, 4])
arr_col = arr.reshape(-1, 1)
print("=== col ===")
print(arr_col, "\n")
arr_2d = arr.reshape(2, 2)
print("=== 2d ===")
print(arr_2d)

=== col ===
[[1]
 [2]
 [3]
 [4]] 

=== 2d ===
[[1 2]
 [3 4]]


In [7]:
# numpy matrix
mat1 = np.matrix([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3]
])
print("=== matrix ===")
print(mat1)

# get col
print("=== col1 ===")
print(mat1[:, 1])

=== matrix ===
[[1 2 3]
 [4 5 6]
 [1 2 3]]
=== col1 ===
[[2]
 [5]
 [2]]


In [11]:
mat2 = np.matrix([
    [1, 2, 3],
    [1, 1, 1],
    [3, 2, 1]
])

# T
print("=== matrix.T ===")
print(mat2.T)

# -1
print("=== matrix^-1 ===")
print(np.linalg.inv(mat2))

=== matrix.T ===
[[1 1 3]
 [2 1 2]
 [3 1 1]]
=== matrix^-1 ===
[[-2.25179981e+15  9.00719925e+15 -2.25179981e+15]
 [ 4.50359963e+15 -1.80143985e+16  4.50359963e+15]
 [-2.25179981e+15  9.00719925e+15 -2.25179981e+15]]


In [12]:
# 点乘
mat3 = np.matrix([
    [1, 2, 3],
    [2, 3, 1],
    [3, 1, 2]
])
vec1 = np.array([1, 2, 1])
vec1_mat2_dot = np.dot(vec1, mat3)
print(vec1_mat2_dot)

[[8 9 7]]


In [31]:
# 最大/最小
mat4 = np.matrix([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("all max: %d, all min: %d" % (mat4.max(), mat4.min()))
print("col max:", mat4.max(axis=0))
print("row max:\n", mat4.max(axis=1))

all max: 9, all min: 1
max per col: [[7 8 9]]
max per row:
 [[3]
 [6]
 [9]]


In [35]:
mat5 = np.matrix([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("all sum: %d" % mat5.sum())
print("col sum:", mat5.sum(axis=0))
print("row sum:\n", mat5.sum(axis=1))

all sum: 45
col sum: [[12 15 18]]
row sum:
 [[ 6]
 [15]
 [24]]
