In [2]:
import numpy as np

In [4]:
# numpy array
arr1 = np.array([1, 2, 3])
arr2 = np.array([
    [1, 2, 3],
    [2, 3, 1],
    [3, 1, 2]
])
print("=== 1d ===")
print(arr1)
print("=== 2d ===")
print(arr2)

=== 1d ===
[1 2 3]
=== 2d ===
[[1 2 3]
 [2 3 1]
 [3 1 2]]


In [36]:
# reshape
arr3 = np.array([1, 2, 3, 4])
arr3_col = arr3.reshape(-1, 1)
print("=== col ===")
print(arr3_col)
arr3_2d = arr3.reshape(2, 2)
print("=== 2d ===")
print(arr3_2d)

=== col ===
[[1]
 [2]
 [3]
 [4]]
=== 2d ===
[[1 2]
 [3 4]]


In [41]:
# create array

# zeros
arr4 = np.zeros((2, 3))
print("=== zeros ===")
print(arr4)

# 0~n
arr5 = np.arange(5)
print("=== range(5) ===")
print(arr5)

# 单元矩阵
arr6 = np.eye(3)
print("=== E ====")
print(arr6)

=== zeros ===
[[0. 0. 0.]
 [0. 0. 0.]]
=== range(5) ===
[0 1 2 3 4]
=== E ====
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
# numpy matrix
mat1 = np.matrix([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3]
])
print("=== matrix ===")
print(mat1)

# get col
print("=== col1 ===")
print(mat1[:, 1])

=== matrix ===
[[1 2 3]
 [4 5 6]
 [1 2 3]]
=== col1 ===
[[2]
 [5]
 [2]]


In [11]:
mat2 = np.matrix([
    [1, 2, 3],
    [1, 1, 1],
    [3, 2, 1]
])

# T
print("=== matrix.T ===")
print(mat2.T)

# -1
print("=== matrix^-1 ===")
print(np.linalg.inv(mat2))

=== matrix.T ===
[[1 1 3]
 [2 1 2]
 [3 1 1]]
=== matrix^-1 ===
[[-2.25179981e+15  9.00719925e+15 -2.25179981e+15]
 [ 4.50359963e+15 -1.80143985e+16  4.50359963e+15]
 [-2.25179981e+15  9.00719925e+15 -2.25179981e+15]]


In [12]:
# 点乘
mat3 = np.matrix([
    [1, 2, 3],
    [2, 3, 1],
    [3, 1, 2]
])
vec1 = np.array([1, 2, 1])
vec1_mat2_dot = np.dot(vec1, mat3)
print(vec1_mat2_dot)

[[8 9 7]]


In [31]:
# 最大/最小
mat4 = np.matrix([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("all max: %d, all min: %d" % (mat4.max(), mat4.min()))
print("col max:", mat4.max(axis=0))
print("row max:\n", mat4.max(axis=1))

all max: 9, all min: 1
max per col: [[7 8 9]]
max per row:
 [[3]
 [6]
 [9]]


In [35]:
mat5 = np.matrix([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("all sum: %d" % mat5.sum())
print("col sum:", mat5.sum(axis=0))
print("row sum:\n", mat5.sum(axis=1))

all sum: 45
col sum: [[12 15 18]]
row sum:
 [[ 6]
 [15]
 [24]]
