In [2]:
import numpy as np

In [3]:
# numpy array
arr1 = np.array([1, 2, 3])
arr2 = np.array([
    [1, 2, 3],
    [2, 3, 1],
    [3, 1, 2]
])
print(arr1)
print(arr2)

[1 2 3]
[[1 2 3]
 [2 3 1]
 [3 1 2]]


In [6]:
# reshape
arr3 = np.array([1, 2, 3])
arr3_col = arr3.reshape(-1, 1)
print(arr3_col)

[[1]
 [2]
 [3]]


In [7]:
# numpy matrix
mat1 = np.matrix([
    [1, 2, 3],
    [2, 3, 1],
    [3, 1, 2]
])
print(mat1)

[[1 2 3]
 [2 3 1]
 [3 1 2]]


In [10]:
# 点乘
mat2 = np.matrix([
    [1, 2, 3],
    [2, 3, 1],
    [3, 1, 2]
])
vec1 = np.array([1, 2, 1])
vec1_mat2_dot = np.dot(vec1, mat2)
print(vec1_mat2_dot)

[[8 9 7]]
