In [1]:
import torch

In [ ]:
'''
tensor (张量) 是 pytorch 的存储和变换数据的主要工具
它类似 numpy 的多维数组, 但它有 GPU 计算, 自动求梯度等多种适合深度学习的功能
'''

In [4]:
torch.rand(2, 2)

tensor([[0.0488, 0.9423],
        [0.2537, 0.9269]])

In [6]:
# 通过数组创建张量
torch.tensor([1, 2])

tensor([1, 2])

In [5]:
x = torch.rand(2, 2)
x.shape

torch.Size([2, 2])

In [8]:
x = torch.tensor([1, 2])
y = torch.tensor([2, 1])
print(x + y)

tensor([3, 3])


In [14]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
# 索引, 这里 y 与 x 指向同一片内存
y = x[1, :]
print(y)

tensor([4, 5, 6])


In [20]:
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
# -1 表示根据其它纬度推断
y = x.view(-1, 6)
print('y', y)
# 这里虽然形状不同, 但数据共享
y += 1
print('x', x)
# 所以如果想要不改变原张量, 要拷贝一个
z = x.clone().view(-1, 6)
print('z', z)
z += 1
print('z', z)
print('x', x)

y tensor([[1, 2, 3, 4, 5, 6]])
x tensor([[2, 3, 4],
        [5, 6, 7]])
z tensor([[2, 3, 4, 5, 6, 7]])
z tensor([[3, 4, 5, 6, 7, 8]])
x tensor([[2, 3, 4],
        [5, 6, 7]])


In [21]:
# 将 1 维张量转化为 Python 数字
x = torch.rand(1)
print(x)
print(x.item())

tensor([0.3573])
0.35725635290145874


In [22]:
# 对角线元素之和
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [3, 2, 1]
])
print(x.trace())

tensor(7)


In [23]:
# 提取对角线元素
x = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [3, 2, 1]
])
print(x.diag())

tensor([1, 5, 1])


In [29]:
# 矩阵乘法
x = torch.tensor([
    [1, 2],
    [2, 1]
])
y = torch.tensor([
    [1, 1],
    [1, 1]
])
print(x.mm(y))

tensor([[3, 3],
        [3, 3]])


In [27]:
# 矩阵转置
x = torch.tensor([
    [1, 1],
    [2, 2]
])
print(x.t())

tensor([[1, 2],
        [1, 2]])


In [42]:
# 内积
x = torch.tensor([1, 2])
y = torch.tensor([1, 1])
print(x.dot(y.t()))

tensor(3)


In [36]:
# 逆矩阵
x = torch.tensor([
    [1, 2],
    [2, 1]
], dtype=int)
# x.float() 将 LongTensor 转化为 FloatTensor
print(x.float().inverse())

tensor([[-0.3333,  0.6667],
        [ 0.6667, -0.3333]])


In [44]:
# 奇异值分解
x = torch.tensor([
    [1, 2],
    [2, 1]
], dtype=int)
print(x.float().svd())

torch.return_types.svd(
U=tensor([[-0.7071, -0.7071],
        [-0.7071,  0.7071]]),
S=tensor([3.0000, 1.0000]),
V=tensor([[-0.7071,  0.7071],
        [-0.7071, -0.7071]]))


In [45]:
# tensor 和 numpy 的互相转化
x = torch.tensor([1, 2, 3])
y = x.numpy()
print('x', x)
print('y', y)
z = torch.from_numpy(y)
print('z', z)

x tensor([1, 2, 3])
y [1 2 3]
z tensor([1, 2, 3])


In [46]:
torch.cuda.is_available()

False